### ISSUE TITLE
Hecate freezes

### ISSUE THREAD

**Issue by evanmiller** [evanmiller/hecate#13]
Hecate almost always freezes after a certain amount of use. I don't think this used to happen... might be some kind of channel communication deadlock. Any ideas, @kaos?

**Comment by kaos** [comment]
Oh.. well, no. Haven’t used it for a very long time now. Any approximate
amount of use? And what kind of operations? If I can get it to freeze I
could see what I can find out.
lör 27 jan. 2018 kl. 13:40 skrev Evan Miller <notifications@github.com>:

**Comment by evanmiller** [comment]
Seems to happen if I navigate around a file a lot, e.g. holding down navigation keys, maybe after a minute or two of "normal" usage. Also happens when searching a large file (500kb). I'm thinking there's some kind of channel deadlock happening?

I'm using an older version of hecate now (f89c125) and it doesn't have the problem. I've tried sending an `ABRT` signal to get a Go stack trace but maybe Termbox is intercepting these. Using latest termbox-go in both cases.

I'll try updating my Go installation to see if that changes anything.

**Comment by kaos** [comment]
Hmm.. I've been navigating and searching in a 3.7M apk file for 15 or so minutes without hiccup now. Jumping about and searching and the only weirdness I found, which may be a feature, was that the cursor changed size (as large as possible, covering any adjacent 0's) and preferred to be int rather than stay at pattern when searching for next match with `n`.

I'm on a Mac with a possibly ancient version of go: `go version go1.8.1 darwin/amd64`.

Only a single open file though... do you have multiple files opened? Read-only or edit mode?

**Comment by evanmiller** [comment]
Hmm okay. I only have one file open. I can freeze reliably within a minute or two.

`go version go1.9 darwin/amd64` (Mac OS High Sierra 10.13.3)

I'm really not sure why I'd see the freezes on my machine but they don't show up on yours.

Are you using the latest Termbox or an older checkout?

**Comment by kaos** [comment]
OSX 10.13.2 here.. no update available either.. ?!

I'm on a really old termbox checkout: https://github.com/nsf/termbox-go/commits/386df883b26025d2b9bb4bc59f846b0bab224ade

**Comment by kaos** [comment]
Unless I'm mistaken, I recompiled with latest termbox and hit around like crazy, still no freeze after ~3minutes.. (I pulled latest termbox-go sources in my Go env src dir and rebuilt hecate).

**Comment by evanmiller** [comment]
Thanks for testing, @kaos. It looks like I had an old hecate build in my path! When I cleared everything out and updated, it works squeaky clean. Sorry for the noise :-/

**Comment by kaos** [comment]
Happy you figured it out. Maybe add the output of `git describe —dirty`
somewhere.. like the about/help page.. ;)

sön 28 jan. 2018 kl. 16:25 skrev Evan Miller <notifications@github.com>:
