### ISSUE TITLE
Hex Editing Features

### ISSUE THREAD

**Issue by Immortalin** [evanmiller/hecate#5]
Hi, 

Can some basic hex editing features be added? E.g. find and replace etc.

Thanks in advance!

**Comment by evanmiller** [comment]
Hope to add editing features in the future -- in the meantime check out the new "Find" feature (press `/` to search the file, `n` to advance to the next match).

**Comment by othias** [comment]
Looking forward to seeing editing features too. Your hecate is the only (?) console hex editor with integer/float types support, which I've long been searching for! Thanks

**Comment by kaos** [comment]
#8 added editing features. Replace is still missing, though.
